# Generated by Django 4.0 on 2021-12-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=100, verbose_name='médico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='data')),
            ],
            options={
                'verbose_name': 'atendimento',
                'verbose_name_plural': 'atendimentos',
                'ordering': ('doctor',),
            },
        ),
    ]
