# Generated by Django 4.0 on 2021-12-16 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_careitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cares', to='exam.patient', verbose_name='paciente'),
            preserve_default=False,
        ),
    ]
