# Generated by Django 4.0 on 2021-12-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_care_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careitems',
            name='is_done',
            field=models.BooleanField(default='', verbose_name='feito?'),
        ),
    ]
